import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Chayse Walker X Vercel Skill Test
        </h1>

        <p className={styles.description}>
          Skill Test Completed on 6/20/2020{' '}
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs-test-eta-dun.vercel.app/Questionone" className={styles.card}>
            <h2>Question 1 &rarr;</h2>
            <p>Imagine that you are the most senior support engineer within a team of 3 people. 
              As the principal, and as platform usage and customer volume grows, youre 
              helping to determine the focus of the team for the following quarter. 
              From this list, pick the 5 highest prioritized actions and 5 lowest 
              prioritized actions youd lead the team on. Explain why you chose those prioritization levels.</p>
          </a>


          <a href="https://nextjs-test-eta-dun.vercel.app/Questiontwo" className={styles.card}>
            <h2>Question 2 &rarr;</h2>
            <p>What do you want to learn, or do more of, at work?</p>
          </a>

          <a
            href="https://nextjs-test-eta-dun.vercel.app/Questionthree"
            className={styles.card}
          >
            <h2>Question 3 &rarr;</h2>
            <p>Imagine you are tasked with the following quarterly project:Build a process for ensuring 
              90% of our paid customers add 2FA (Two-Factor Authentication).
              Spend 10 minutes outlining how you would approach this directive and execute on it.</p>
          </a>

          <a
            href="https://vercel.com"
            className={styles.card}
          >
            <h2>Question 4 &rarr;</h2>
            <p>
            Add a temporary in-app redirect to your project, redirecting /hello-vercel (or any path –
            but be sure to tell us which!) to vercel
            </p>
          </a>

          <a
            href="https://nextjs-test-eta-dun.vercel.app/Questionfive"
            className={styles.card}
          >
            <h2>Question 5 &rarr;</h2>
            <p>
            A customer writes in to the Helpdesk stating: I have a custom domain which I
            purchased at GoDaddy and I want to use it on my project. In a couple of paragraphs,
            how do you respond?
            </p>
          </a>

          <a
            href="https://nextjs-test-eta-dun.vercel.app/Questionsix"
            className={styles.card}
          >
            <h2>Question 6 &rarr;</h2>
            <p>
            A user writes in with the following problem: “On our team, GitHub commits by user 
            janedoe@helloworld.com dont trigger any deployments. 
            Commits by other users work fine. Other projects work fine. 
            Help! What can we do to fix this?” How would you approach debugging this problem? 
            What questions would you ask, either internally or of the user? 
            Write a response which you would send back to this user.
            </p>
          </a>

          <a
            href="https://nextjs-test-eta-dun.vercel.app/Questionseven"
            className={styles.card}
          >
            <h2>Question 7 &rarr;</h2>
            <p>
            What do you think is one of the most common problems which customers ask 
            Vercel for help with? How would you help customers 
            to overcome common problems, short-term and long-term?
            </p>
          </a>

          <a
            href="https://nextjs-test-eta-dun.vercel.app/Questioneight"
            className={styles.card}
          >
            <h2>Question 8 &rarr;</h2>
            <p>
            How could we improve or alter this familiarization exercise?
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
