import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Chayse Walker X Vercel Skill Test
        </h1>

        <p className={styles.description}>
          Skill Test Completed on 6/20/2020{' '}
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs-test-eta-dun.vercel.app/Questionone" className={styles.card}>
            <h2>Question 1 &rarr;</h2>
            <p>Imagine that you are the most senior support engineer within a team of 3 people. 
              As the principal, and as platform usage and customer volume grows, you’re 
              helping to determine the focus of the team for the following quarter. 
              From this list, pick the 5 highest prioritized actions and 5 lowest 
              prioritized actions you’d lead the team on. Explain why you chose those prioritization levels.</p>
          </a>


          <a href="https://nextjs-test-eta-dun.vercel.app/Questiontwo" className={styles.card}>
            <h2>Question 2 &rarr;</h2>
            <p>What do you want to learn, or do more of, at work?</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
