import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Question 8
        </h1>
        <p>I would improve this exercise by having links to direct people to a get started guide and proper 
            documentation to be better prepared. My experience was not smooth when attempting to access links in this document.</p>

        <p>Also I would include a video tutorial on nextjs or vercel in general to get people up to speed on platform.</p>
      </main>
    </div>
  );
}