import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Question 1
        </h1>
        <p>5 Highest</p>

<p>1. Write and maintain support articles and docs pages</p>

<p>2. Analyze hundreds of support tickets to spot trends the product team can use</p>

<p>3. Help train and onboard new support teammates</p>

<p>4. Work with engineering teams during incidents and provide updates to internal and external stakeholders</p>

<p>5. Act as a dedicated CSE for a handful of key customers to ensure their success using Vercel</p>

<p>The reason for choosing the above prioritization levels is to maintain the integrity of the support engineer&rsquo;s role. The above list is focused on practices and processes that give the support team scalability. By documenting and maintaining a knowledge base, new hires plus existing staff can learn how to quickly adapt to issues that may be unknown. This helps removes bottlenecks from the support process and creates a healthy relationship with the customer. Working with other engineering teams is essential as well. Good communication in a support role is the most overlooked skill. When not done correctly it can create a huge problem for engineers and customer expectations.</p>

<p>5 Lowest</p>

<p>1. Help resolve billing issues for customers</p>

<p>2. Manage a support team</p>

<p>3. Respond to queries on Twitter, Reddit, Hacker News and other 3rd party sites</p>

<p>4. Engage multiple users at once in a public discussion, to answer their questions and troubleshoot problems</p>

<p>5. Work with people to figure out if Vercel is suitable for their use case</p>

<p>The above list seemed to be most remote to the support engineer&rsquo;s role. Billing issues, QA sessions and internal management are tasks that are easily done by other groups/members of an organization. Though they are important they are not essential to the growth of a Support team. </p>
      </main>
    </div>
  );
}