import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Question 7
        </h1>
        <p>I think the most common question is how to integrate domain to Vercel.</p>
        <p>I would help customers overcome common problems by creating documentation that is clearly written and 
    easy to follow when these issues arise. I would also work with our internal engineering teams to 
           create better processes, so the issues appear less. </p>
      </main>
    </div>
  );
}