import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Question 3
        </h1>
        <p>1. Educate our paid customers on the importance of 2FA.</p>

    <p>2. Conduct surveys for Paid customers to determine best 2FA authentication method.</p>

    <p>a. SMS TOKEN</p>

    <p>b. EMAIL TOKEN</p>

    <p>c. HARDWARE TOKEN</p>

    <p>d. SOFTWARE TOKEN</p>

    <p>e. PHONE CALL</p>

    <p>f. BIOMETRIC VERIFICATION</p>

    <p>3. Work with internal stakeholders on best 2FA method(s) to use.</p>

    <p>4. Create 2FA process using best method from surveys/consultation.</p>

    <p>5. Q/A and Test the 2FA process with 3 live accounts.</p>

    <p>6. Implement and Deploy </p>
      </main>
    </div>
  );
}